version: 2.1
orbs:
  node: circleci/node@3.0.1
  docker: circleci/docker@1.3.0

jobs:
  build-app:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: node --version
      - persist_to_workspace:  # make available for future steps
          root: .

workflows:
  build:
    jobs:
      - build-app
      - docker/publish:
        context: matt_dockerhub
        requires:
          - build-app
        image: mattbrabazon/node-poc
        attach-at: ./  # default?
        path: ./   # default?
        docker-username: DOCKER_LOGIN
        docker-password: DOCKER_PASSWORD