version: 2.1
orbs:
  node: circleci/node@3.0.1
  docker: circleci/docker@1.3.0
jobs:
  build-app:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: node --version
      - run: npm run build
      - run: |
                set -xu
                mkdir artifact
                cp -r dist artifact/dist
                cp -r server artifact/server
                cp package*.json artifact
                cp app.js artifact
                ls -lah
      - persist_to_workspace:  # make available for future steps
          root: .
          path: ~/project
      - store_artifacts:
          path:  ~/project/artifact
workflows:
  build:
    jobs:
      - build-app
      - node/test:
          matrix:
            parameters:
              version:
                - 14.6.0
                - 12.18.3
                - 10.22.0
      - docker/publish:
          requires:
            - build-app
            - node/test
          context: matt_dockerhub
          image: mattbrabazon/node-poc
          attach-at: ./ 
          path: ~/project
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD