version: 2.1
orbs:
  node: circleci/node@3.0.1
  docker: circleci/docker@1.3.0
jobs:
  build-app:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: node --version
      - persist_to_workspace:  # make available for future steps
          root: .
workflows:
  build:
    jobs:
      - build-app
      - docker/publish:
          requires:
            - build-app
          context: matt_dockerhub
          image: mattbrabazon/node-poc
          attach-at: ./ 
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD